language: python
python:
- 2.7
install:
- pip install .
script: py.test
notifications:
  irc:
    channels:
    - irc.freenode.org#majerteam-travis
    on_success: change
deploy:
  provider: pypi
  user: tonthon21
  password:
    secure: gE7lEc93UP3dOzR1XtngMkIhTl152xqNTEg1IUKMminM3FqP8rYTmvYW8Q31u4yWIff3Qemb8tYwOvROME2Ffn1oyKLHpPH3skR91UfX0W2g6DxLcX508uLFrTrlZEqEjrqoYkwcYXot4z44glYL8hlkC/c5J7qZ9Ovvt5ICfcE=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: majerteam/sqla_inspect
